Repository Tran-Antoine/sphinx, pull requests merged in 2021-01, with the labels that each got.

#22 feat: add 'toml to question' converter
  api/build.gradle
  api/src/main/java/net/starype/quiz/api/game/answer/AlwaysValid.java
  api/src/main/java/net/starype/quiz/api/game/answer/Answer.java
  api/src/main/java/net/starype/quiz/api/game/answer/BinaryLossFunction.java
  api/src/main/java/net/starype/quiz/api/game/answer/CleanSeparatorProcessor.java
  api/src/main/java/net/starype/quiz/api/game/answer/CorrectAnswerFactory.java
  api/src/main/java/net/starype/quiz/api/game/answer/DoubleAnswerFactory.java
  api/src/main/java/net/starype/quiz/api/game/answer/ExactAnswerCorrectness.java
  api/src/main/java/net/starype/quiz/api/game/answer/ExactAnswerEvaluator.java
  api/src/main/java/net/starype/quiz/api/game/answer/IdentityProcessor.java
  api/src/main/java/net/starype/quiz/api/game/answer/IntegerAnswerFactory.java
  api/src/main/java/net/starype/quiz/api/game/answer/MultipleChoiceAnswer.java
  api/src/main/java/net/starype/quiz/api/game/answer/MultipleChoiceAnswerFactory.java
  api/src/main/java/net/starype/quiz/api/game/answer/MultipleChoiceCorrectness.java
  api/src/main/java/net/starype/quiz/api/game/answer/MultipleChoiceValidity.java
  api/src/main/java/net/starype/quiz/api/game/answer/RemoveSpecialCharProcessor.java
  api/src/main/java/net/starype/quiz/api/game/answer/TrueFalseProcessor.java
  api/src/main/java/net/starype/quiz/api/game/answer/WordAnswerFactory.java
  api/src/main/java/net/starype/quiz/api/game/question/DefaultQuestion.java
  api/src/main/java/net/starype/quiz/api/parser/BinaryLossMapper.java
  api/src/main/java/net/starype/quiz/api/parser/CleanSeparatorProcessorMapper.java
  api/src/main/java/net/starype/quiz/api/parser/CleanStringProcessorMapper.java
  api/src/main/java/net/starype/quiz/api/parser/ConfigMapper.java
  api/src/main/java/net/starype/quiz/api/parser/ConfigMatcher.java
  api/src/main/java/net/starype/quiz/api/parser/DifficultyMapper.java
  api/src/main/java/net/starype/quiz/api/parser/DoubleEvaluatorMapper.java
  api/src/main/java/net/starype/quiz/api/parser/ExactEvaluatorMapper.java
  api/src/main/java/net/starype/quiz/api/parser/IntegerEvaluatorMapper.java
  api/src/main/java/net/starype/quiz/api/parser/LinearLossMapper.java
  api/src/main/java/net/starype/quiz/api/parser/MCQEvaluatorMapper.java
  api/src/main/java/net/starype/quiz/api/parser/PartialEvaluator.java
  api/src/main/java/net/starype/quiz/api/parser/QuestionParser.java
  api/src/main/java/net/starype/quiz/api/parser/TrueFalseProcessorMapper.java
  api/src/main/java/net/starype/quiz/api/parser/WorldEvaluatorMapper.java
  api/src/main/java/net/starype/quiz/api/util/StringUtils.java
  api/src/main/resources/questions/algebra/q1.toml
  api/src/test/java/net/starype/quiz/api/game/answer/DoubleAnswerEvaluatorTest.java
  api/src/test/java/net/starype/quiz/api/game/answer/IntegerAnswerTest.java
  api/src/test/java/net/starype/quiz/api/game/answer/MultipleChoiceAnswerTest.java
  api/src/test/java/net/starype/quiz/api/game/answer/WordAnswerTest.java
  api/src/test/java/net/starype/quiz/api/reader/QuestionParserTest.java
Labels: enhancement

#21 feat: add database for accelerated file parsing
  .gitignore
  api/src/main/java/net/starype/quiz/api/parser/Argument.java
  api/src/main/java/net/starype/quiz/api/parser/ArgumentValue.java
  api/src/main/java/net/starype/quiz/api/parser/DBEntry.java
  api/src/main/java/net/starype/quiz/api/parser/DBInputOutput.java
  api/src/main/java/net/starype/quiz/api/parser/DBParser.java
  api/src/main/java/net/starype/quiz/api/parser/DBTable.java
  api/src/main/java/net/starype/quiz/api/parser/IndexDatabase.java
  api/src/main/java/net/starype/quiz/api/parser/IndexQuery.java
  api/src/main/java/net/starype/quiz/api/parser/TrackedDatabase.java
  api/src/main/java/net/starype/quiz/api/util/ByteBufferUtils.java
  api/src/main/java/net/starype/quiz/api/util/CheckSum.java
  api/src/main/java/net/starype/quiz/api/util/FileUtils.java
  api/src/main/java/net/starype/quiz/api/util/SerializedArgument.java
  api/src/main/java/net/starype/quiz/api/util/Serializer.java
  api/src/test/java/net/starype/quiz/api/reader/DBTest.java
Labels: enhancement

#26 feat: add search system and standalone database
  .gitignore
  api/src/main/java/net/starype/quiz/api/parser/Argument.java
  api/src/main/java/net/starype/quiz/api/parser/ArgumentValue.java
  api/src/main/java/net/starype/quiz/api/parser/BinaryLossMapper.java
  api/src/main/java/net/starype/quiz/api/parser/CleanSeparatorProcessorMapper.java
  api/src/main/java/net/starype/quiz/api/parser/CleanStringProcessorMapper.java
  api/src/main/java/net/starype/quiz/api/parser/ConfigMapper.java
  api/src/main/java/net/starype/quiz/api/parser/ConfigMatcher.java
  api/src/main/java/net/starype/quiz/api/parser/DBEntry.java
  api/src/main/java/net/starype/quiz/api/parser/DBInputOutput.java
  api/src/main/java/net/starype/quiz/api/parser/DBParser.java
  api/src/main/java/net/starype/quiz/api/parser/DBTable.java
  api/src/main/java/net/starype/quiz/api/parser/DifficultyMapper.java
  api/src/main/java/net/starype/quiz/api/parser/DoubleEvaluatorMapper.java
  api/src/main/java/net/starype/quiz/api/parser/ExactEvaluatorMapper.java
  api/src/main/java/net/starype/quiz/api/parser/FileParser.java
  api/src/main/java/net/starype/quiz/api/parser/FileSerializeIO.java
  api/src/main/java/net/starype/quiz/api/parser/IndexQuery.java
  api/src/main/java/net/starype/quiz/api/parser/IntegerEvaluatorMapper.java
  api/src/main/java/net/starype/quiz/api/parser/LinearLossMapper.java
  api/src/main/java/net/starype/quiz/api/parser/MCQEvaluatorMapper.java
  api/src/main/java/net/starype/quiz/api/parser/QuestionDatabase.java
  api/src/main/java/net/starype/quiz/api/parser/QuestionParser.java
  api/src/main/java/net/starype/quiz/api/parser/QuestionQuery.java
  api/src/main/java/net/starype/quiz/api/parser/ReadableMap.java
  api/src/main/java/net/starype/quiz/api/parser/SerializedIO.java
  api/src/main/java/net/starype/quiz/api/parser/TrackedDatabase.java
  api/src/main/java/net/starype/quiz/api/parser/TrueFalseProcessorMapper.java
  api/src/main/java/net/starype/quiz/api/parser/WordEvaluatorMapper.java
  api/src/main/java/net/starype/quiz/api/util/CheckSum.java
  api/src/main/java/net/starype/quiz/api/util/RandomComparator.java
  api/src/main/java/net/starype/quiz/api/util/SerializedArgument.java
  api/src/main/java/net/starype/quiz/api/util/StringUtils.java
  api/src/test/java/net/starype/quiz/api/reader/DBTest.java
  api/src/test/java/net/starype/quiz/api/reader/QuestionDBTest.java
  api/src/test/java/net/starype/quiz/api/reader/QuestionParserTest.java
Labels: awaiting, enhancement

#30 fix: minor behavior-related issue in race and individual round
  api/src/main/java/net/starype/quiz/api/game/ClassicalRound.java
  api/src/main/java/net/starype/quiz/api/game/FixedLeaderboardEnding.java
  api/src/main/java/net/starype/quiz/api/game/IndividualRound.java
  api/src/main/java/net/starype/quiz/api/game/RaceRound.java
  api/src/main/java/net/starype/quiz/api/game/ScoreDistribution.java
  api/src/main/java/net/starype/quiz/api/game/answer/BinaryLossFunction.java
  api/src/main/java/net/starype/quiz/api/game/answer/WordValidityEvaluator.java
  api/src/test/java/net/starype/quiz/api/game/RaceRoundTest.java
Labels: bug

#31 improvement: add abstraction and unit tests
  api/src/main/java/net/starype/quiz/api/parser/FileInput.java
  api/src/main/java/net/starype/quiz/api/parser/FileParser.java
  api/src/main/java/net/starype/quiz/api/parser/FileSerializedIO.java
  api/src/main/java/net/starype/quiz/api/parser/QuestionDatabase.java
  api/src/main/java/net/starype/quiz/api/parser/QuestionParser.java
  api/src/main/java/net/starype/quiz/api/parser/SimpleFileInput.java
  api/src/main/java/net/starype/quiz/api/parser/SimpleQuestionDatabase.java
  api/src/main/java/net/starype/quiz/api/parser/TrackedDatabase.java
  api/src/main/java/net/starype/quiz/api/util/CollectionUtils.java
  api/src/test/java/net/starype/quiz/api/reader/DBTest.java
  api/src/test/java/net/starype/quiz/api/reader/QuestionDBTest.java
  api/src/test/java/net/starype/quiz/api/reader/SimpleQuestionDatabaseTest.java
  api/src/test/java/net/starype/quiz/api/reader/StringUtilsTest.java
Labels: enhancement

#35 improvement: round result display with leaderboard image + minor changes in the report system
  api/src/main/java/net/starype/quiz/api/game/ClassicalRound.java
  api/src/main/java/net/starype/quiz/api/game/GameRound.java
  api/src/main/java/net/starype/quiz/api/game/GameRoundContext.java
  api/src/main/java/net/starype/quiz/api/game/GameRoundReport.java
  api/src/main/java/net/starype/quiz/api/game/IndividualRound.java
  api/src/main/java/net/starype/quiz/api/game/PollRound.java
  api/src/main/java/net/starype/quiz/api/game/RaceRound.java
  api/src/main/java/net/starype/quiz/api/game/ScoreDistribution.java
  api/src/main/java/net/starype/quiz/api/game/SimpleGame.java
  api/src/main/java/net/starype/quiz/api/game/SimpleGameReport.java
  api/src/main/java/net/starype/quiz/api/game/question/DefaultQuestion.java
  api/src/main/java/net/starype/quiz/api/util/SortUtils.java
  api/src/test/java/net/starype/quiz/api/game/ClassicalGameSample.java
  api/src/test/java/net/starype/quiz/api/game/mock/MockQuestion.java
  api/src/test/java/net/starype/quiz/api/game/mock/MockServer.java
  discord-impl/src/main/java/net/starpye/quiz/discordimpl/command/CreateLobbyCommand.java
  discord-impl/src/main/java/net/starpye/quiz/discordimpl/command/JoinLobbyCommand.java
  discord-impl/src/main/java/net/starpye/quiz/discordimpl/command/NextRoundCommand.java
  discord-impl/src/main/java/net/starpye/quiz/discordimpl/command/SubmitCommand.java
  discord-impl/src/main/java/net/starpye/quiz/discordimpl/core/BotMain.java
  discord-impl/src/main/java/net/starpye/quiz/discordimpl/game/DiscordGameServer.java
  discord-impl/src/main/java/net/starpye/quiz/discordimpl/game/DiscordQuizGame.java
  discord-impl/src/main/java/net/starpye/quiz/discordimpl/game/GameLobby.java
  discord-impl/src/main/java/net/starpye/quiz/discordimpl/game/LobbyList.java
  discord-impl/src/main/java/net/starpye/quiz/discordimpl/input/MessageInputListener.java
  discord-impl/src/main/java/net/starpye/quiz/discordimpl/input/ReactionInputListener.java
  discord-impl/src/main/java/net/starpye/quiz/discordimpl/util/ImageUtils.java
  discord-impl/src/main/resources/frame.png
  discord-impl/src/main/resources/lobby.png
Labels: enhancement

#37 improvement: remove file dependency of database to add flexibility
  .gitignore
  api/src/main/java/net/starype/quiz/api/database/EntryUpdater.java
  api/src/main/java/net/starype/quiz/api/database/FileEntryUpdater.java
  api/src/main/java/net/starype/quiz/api/database/FileInput.java
  api/src/main/java/net/starype/quiz/api/database/FileParser.java
  api/src/main/java/net/starype/quiz/api/database/FilePathReader.java
  api/src/main/java/net/starype/quiz/api/database/QuestionDatabases.java
  api/src/main/java/net/starype/quiz/api/database/SerializedIO.java
  api/src/main/java/net/starype/quiz/api/database/SimpleDatabase.java
  api/src/main/java/net/starype/quiz/api/database/SimpleFileInput.java
  api/src/main/java/net/starype/quiz/api/database/SimpleFilePathReader.java
  api/src/main/java/net/starype/quiz/api/database/SimpleQuestionDatabase.java
  api/src/main/java/net/starype/quiz/api/database/TrackedDatabase.java
  api/src/main/java/net/starype/quiz/api/parser/QuestionParser.java
  api/src/main/java/net/starype/quiz/api/util/FileUtils.java
  api/src/test/java/net/starype/quiz/api/reader/QuestionDBTest.java
Labels: duplicate, enhancement
